language: node_js
node_js:
- node
notifications:
  email:
  - planavsky82@gmail.com
sudo: required
addons:
  chrome: stable
  apt:
    packages:
    - sshpass
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
  only:
  - master
  - release-ultimate-list
after_success:
- ORIGINAL=$(npm view ultimate-list version) && echo $ORIGINAL
before_deploy:
- echo 'PRE DEPLOYMENT'
- ls
- npm run build
- ls
- cd dist
- cd ultimate-list
deploy:
  provider: npm
  email: planavsky82@gmail.com
  api_key:
    secure: kl5W3xQ8P6GcNaiwsYJkclSUQAeWvmuj/D8M3TmaXWgE2i5O8wPh+CLBpmDErFsEmCERYJ9UhRZiG5aJ95WM0AMIxPr3MsSfHt7ur4hgclRgCTDIvhtVRGuY+HTX8quN4pfgr090svlM7Fb3dVYmcBVgwSQzd9Jy1i5HXRlyn+TJEZrh02ULe74PmUOxIQ1Us6eQbYGxV05EPKJkoIP4g00IZRuL4YvKMz2IaBjhrarm1uglNFHA+OpIdGrVqZBC6KbMs0m2wNsjfQCOliLgMzKWrCo0z4j50Am/ignzr2ja81CbtguYMFDXsWyrMilpr8/BbaQ9a2fYgiZPzc/Jz/Q7VzQ6DHD2xHyMoEt11/u9LlEJBNePd9wmnRB9KkpCFcelKHfcteuqIa/YLMFpTop6qPPbCoI/acoYQRFA4+cUHl7tlWUlblYhe6UdwqgzRDqh6oCF5s2u1hbA94CL9TTMiA7UZcwdypHbH/JNLx5SG8rBjgc1IYXJgf05+Dj1xTDW7ZyhCfZYNe6Po0IoD71g8qWaPngaxMziPs2tJPQESDXhFu3ndeHWFlbN6Ql+BIbzQI455i5YBPsTeOjiQcOYw80+slqbVbNz1AsV0tSHFGIivfuMTnkyCGvHyz/HkxOLDFJb6/irg4NpMNFKkDzvRM8bOC6pVmhGmhi7Mik=
  skip_cleanup: true
  on:
    tags: false
    branch: release-ultimate-list
    repo: planavsky82/planavsky-com
after_deploy:
- echo 'POST DEPLOYMENT'
- cd ..
- cd ..
- cd projects
- cd ultimate-list
- echo $ORIGINAL
- NEW=$(npm view ultimate-list version) && echo $NEW
- PACKAGE_VERSION=$(node -p "require('./package.json').version")
- echo $PACKAGE_VERSION
- "../../scripts/finalize.sh;"
env:
  global:
  - secure: X8eiNr6nP8eN7nWAiOfPyo22D03NBT7mJ7hrakZLQVqGWuVieo5MtIJNkGT9Bh+EIgXTzNhmPKPgEY0z6OD18ZRe9+g3crz1FC3j6q14MFnAhxWnmSQFJWj5LtPARff/GSpp6YdXiCUD9UPtki1n9vTa2UKah0DGUYBydHuNQrOAbQNoVnJv2bXxhjonGvBJosG8JSpxBNQfCmMdyrV5wdSXFyASUBZkxoV8jNQiaqrP4sxSraGN/VYq46s9RLAdxW/UCWFAYh0QXWcA20rsD4my71DFFdvAn694UzTgj5mH2BobWTqWPK0RAqgMymj3UTnYfIZXIRsGtcoSOye6Zk+1FVpP0umZCwqkpw2bAMLgRcCubFtgNkXCE8gbI0vUaekZmoYlOw/t+GXre5iq8f96Alxqdvvj/002PVSkaR1oeCTg4tQNejXdIqErwMQ6Rs3t1BJzGF+YFYtcFhk7RfmBjNkpAvyhMmIFoBN/lpDXLvkAeI3y2C/OvvrhCFK7EPCYzuyoolOdJgJlPXcWL+UH9IKs1vdbDVziysqTiijBp1YjL8Qzu2IuVabANsWWJzFDgEeNuF40TE+T+caGA0Gh9RKnc3AsAg+1N+yLp20qcIDfZLXnOROa/bFq09EyZKG0ssvpDbO5cIsE01EgdOYIBDltw93rTMsxeAVxmw8=
  - secure: EayT+LmrJqul0t1tOMV7wukH937+V/4gEgXy1ovuPALxLP0VS2xQ7lCk4UpNt1gQKTfNvUWI6MwXzMEYEz5DYARxvH8S7R5DY6OZdHNHqiRcr2OJ50xvbDT+Y7AFhPpa3za+EoWSwbOSjmlhkfjZjbWDpsB+hxYHPiLwbvXf4G6L5lExpx+K/xrj7HOS/eqYZtSAS005f1Dt5rbbhBOW/VqPqD8RtfPoRC8qs3fMfHWTuqBLug8C7OUqG6/c9lE+B+J1eM3PotPyi3A2k1W9ihA9ZO3qTpZPnnJVqCdkvjz7hYKtxJfLiEpjEcNWntoT7Ch46SPrTSqerE1lGXbw4K3ihD2/Cc8rxyLdmeBDuf0WYgkjRNqFY5KpSBez/wfz/A3J3fzcsmzEDCVneEpeb0BFkYs9LgL1d8DEr/aP+HAGDenwkVtusLnXOOXBDfmb4mnoRNTutsKS7N1F+NxBX6SNqB5HKVTL5sdnU/Ey6NntUMTy4Ni49H3/1S7PXLZEYp1WmYM1/Xr2FUdtazpWMCSuxu0u1piB2eCIyVE+SH3YLaEGo2Et6VyczKrxc2NWkErJfKqeLC3+L5w3R/hTlKrpOz9t9fRYwdP3YffAi9sFCJzVg2TtvPRJqzb8+Og4Gq15gi9WyPS2/eX5XBnUfwTthYh+XekV4qTHq97x8Qs=
  - secure: Mvh2ixbHxoYH8StiybJFJ1BOePZ6z5upcUy9mMOMBxoRSTr/KWnEzgTkKaX1rRaTiQXHb7RYxPpb2wGtVofIQKFdXtQmae1ekKdPKFxNe2exxH5X5DYWS/kPF9AfvN33Vye+3fE5WMDLR1CX/V1xJVBzI7oKZW+SUCEAlOHlO6Nd7k/Mst3boEGVLJ3Lo+uJ3dALq+IsJvyguMx3dMBcDh5s3lZGwEF8i9Ac1Op85/G6Lf5ALkonvy8nvX3Xvk+gBCGjw1rUIaM4xrwoNHQJwY5BqsZRW1mwICdhy21V4SmDg65pFsvruP0ipeKMgOY2eV4uzWMXxmdTBWBuJuD8oDE6cXKKL0oYn7cewqpBRrjQLnXdIQ31eK8iObxr2c5yKBZLu7Ou7fbrhqV8bQXiQBNts95Aul9my8uG7VQ4Jd9RWnVIS2DLlvlcWsxEm56SJV2T2VNy9Wq47k4/y7Avk/kvKf7fZmBgH1u4bpiKHq7pdBLPSvTtNUIgIl0x5Dt44pdBAtX28H9SLTsocvMoFut/sNHvh+wWOKp2R//VNI/uTH9paG1gDPQ+Me6XwLSn4pxtz5jnk7iObEBjKnvReeMvSf76xf1oJW42JNh8TmsrzxN/wJZLycb5ybxwSie0w26nQHoOLgCUsG1JCrfgi2iVQBNya6c6RWHpvhLH+60=
  - secure: K9kwbaCr34bUr6i5U44npHj0RRUqH7IW+ecppceBye+CBGAvXaEv4GgRYeuRFAm5qgEctshmuijqZlBtMDKz6QylogVIMUMVcGkSP14RDhfapdPHL9bDJ7evzR0V+BYGGeMaQLaRWUO3Xmm5VdaXd35zrjzmLS3+6SUUyTqpgSDicagE3Satl2FgMAYpLjOk14rDSqkvN+QtSdpnBExUSTynoWTTXQFZ0bSVFWgck3yjkoYYCN65j75V8UJD1cZ6mMet4wcBPiITzdhk24h9WlDeuVd7NxpVL3h1iVhQxv6X6BJY01rvOdS4QJbeVmcvgFLLhK8kFWs16dsmF0gvZOO76B1wYoLwgaJz/YRWY1LMsiyc1wuYXiSdExv3ywbZ2nM46s1kI05EprejuFGmR1ezg/MiwtI5vaCkBO2+vJUChtB8W79Ugi7QrvuuNNJf2Sfy4o2WzlGJSmvcV7pHpGVKGmd7FyydT4+FFd8hQV8VyTiu3jDR9HUuwRiDZuKvamMV7boTZjnsCnsRRvkU9W/wEeoQKUrlGfcWKY69AgbKOGoRXbcqBaSEabe1O//ww9YKLozmNGRl6VthUi0BWeOAQWDWQH57Xjc0oYRTn8cKXqKVL6r0F/5S1BNVqnh6djjJeMogDk4lVow0BRm0D79/GNbqOOjhAvIEFMlRbso=
  - secure: uJlyjWfXhwz/4g7nUQ52iPRS/QbrdU3sSxmDbHzBv8fBex8yr9X1fIT7zSEImxjgWL+jDfZm2+P7YI5JP+ossNALlYRqM+BK1+1/c2kHzENpFr1IscCAur7iXAPNbhY/CyA37Aus/cwa88RPNx00oH0/89LvSdgRJ05NjP6GE9O3do5/Jql+5IdLFBOcAA5faNb2kzOn6Rqz+8QGl3zxhDrQaMFqn0XtHXXU/To4tUZTrFw0CwcDjlLFHZGnYIY8N9zREea+gXmKVBPG9Xjonegfh2NKI4Xr78oJNslYfACA8oB5D1D4OBwyKb9Ul9r6QK9Ji06bhqOtdKMZjvjux6dnb3G/jHZ0n93mtPA61YPZL6EYtKQFupH6IIKQTKn1nbYUMP1/8/ELmclkDfsjgK+qT0zVphSSDKSsEb2DvbV3wjLbkREbJr2OKp7POEBXPwFpDLSP/Fck4lphn9YvORZHi7AdcDeuDxLPQ0pzCAqVQM5qguD6PKpMgxb7PMSjdGmc+w7OKaDKEB0DDflJthFQqlCzpU20FOGGAh3TWxXelAdnSJnomJFd2XsdKJD9rAVGTjXWOo5h/gjN7GTBCPdwuy1ctS49QHN1SiRU/1S2zyM5UhPWBpb3NjC8WdI+Yy6PY7eAoBoes+9+xIErt9m4XioUFRYYeEnxa/rJero=
